# -------------------------------------------------------------------------------
# Filename:     Dockerfile.16.04
# UpdateDate:   2021/01/25
# Description:  Build docker images for mlu220-cross-compile.
# Example:      
# Depends:      neuware-mlu270-$VERSION-1_Ubuntu16.04_amd64.deb
#               gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu.tgz
#               gcc-arm-none-eabi-8-2018-q4-major.tar.gz
# Notes:
# -------------------------------------------------------------------------------

FROM ubuntu:16.04

MAINTAINER <Cambricon, Inc.>

WORKDIR /opt/cambricon/

ARG neuware_package=neuware-mlu270-1.4.0-1_Ubuntu16.04_amd64.deb
ARG mlu_platform=MLU270
ARG with_neuware_installed=no

ARG mlu220_gcc_linaro=gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu.tgz
ARG with_gcc_linaro_installed=yes

ARG mlu220_gcc_arm=gcc-arm-none-eabi-8-2018-q4-major.tar.gz
ARG with_gcc_arm_installed=no

RUN echo -e 'nameserver 114.114.114.114' > /etc/resolv.conf

RUN echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted > /etc/apt/sources.list && \
    echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted >> /etc/apt/sources.list && \
    echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial universe >> /etc/apt/sources.list && \
    echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates universe >> /etc/apt/sources.list && \
    echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial multiverse >> /etc/apt/sources.list && \
    echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates multiverse >> /etc/apt/sources.list && \
    echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse >> /etc/apt/sources.list && \
    echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted >> /etc/apt/sources.list && \
    echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security universe >> /etc/apt/sources.list && \
    echo deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security multiverse >> /etc/apt/sources.list && \
    apt-get install --assume-yes && apt-get update --fix-missing && \
    rm -rf /var/lib/apt/lists/* && mkdir /var/lib/apt/lists/partial && \
    apt-get clean && apt-get update --fix-missing && \
    apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
            curl git wget vim build-essential cmake make apt-utils\
            libopencv-dev \
            libgoogle-glog-dev \
            openssh-server \
            libsdl2-dev  \
            lcov  \
            net-tools && \
    apt-get clean && \
    apt-get update --fix-missing && \
    rm -rf /var/lib/apt/lists/*

COPY . /opt/cambricon/

RUN if [ "$with_neuware_installed" = "yes" ]; then dpkg -i /opt/cambricon/$neuware_package && \
    apt -o Accquire::AllowInsecureRepositories=true update && \
    apt install -y cndev cndrv cnrt cncodec && \
    rm -rf /opt/cambricon/$neuware_package; fi && \
    if [ "$with_gcc_linaro_installed" = "yes" ]; then tar zxf /opt/cambricon/$mlu220_gcc_linaro -C /opt/cambricon && \
    echo 'export PATH="/opt/cambricon/gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu/bin:$PATH"' >> /etc/profile && \
    rm -rf /opt/cambricon/$mlu220_gcc_linaro; fi && \
    if [ "$with_gcc_arm_installed" = "yes" ]; then tar zxf /opt/cambricon/$mlu220_gcc_arm -C /opt/cambricon && \
    echo 'export PATH="/opt/cambricon/gcc-arm-none-eabi-8-2018-q4-major/bin:$PATH"' >> /etc/profile && \
    rm -rf /opt/cambricon/$mlu220_gcc_arm; fi

WORKDIR /opt/cambricon
